=== zainbhaila/MeeshQuest/MeeshQuest-Part1/part1in.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!--    definition of simple elements    -->
<!--    Corrected for Fall 2018 -->
<xs:simpleType name="colorType">
<xs:restriction base="xs:string">
<xs:enumeration value="red"/>
<xs:enumeration value="green"/>
<xs:enumeration value="blue"/>
<xs:enumeration value="yellow"/>
<xs:enumeration value="purple"/>
<xs:enumeration value="orange"/>
<xs:enumeration value="black"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="sortType">
<xs:restriction base="xs:string">
<xs:enumeration value="name"/>
<xs:enumeration value="coordinate"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="cityName">
<xs:restriction base="xs:string">
<xs:pattern value="[_a-zA-Z][_a-zA-Z0-9]*"/>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="fileName">
<xs:restriction base="xs:string">
<xs:pattern value="[\w_.]+"/>
</xs:restriction>
</xs:simpleType>
<!--    definition of attributes    -->
<xs:attributeGroup name="commandAtts">
<xs:attribute name="spatialWidth" type="xs:integer" use="required"/>
<xs:attribute name="spatialHeight" type="xs:integer" use="required"/>
</xs:attributeGroup>
<!--    definition of complex types    -->
<xs:complexType name="emptyType"/>
<xs:complexType name="nameType">
<xs:attribute name="name" type="cityName" use="required"/>
</xs:complexType>
<xs:complexType name="cityType">
<xs:attribute name="name" type="cityName" use="required"/>
<xs:attribute name="x" type="xs:integer" use="required"/>
<xs:attribute name="y" type="xs:integer" use="required"/>
<xs:attribute name="radius" type="xs:integer" use="required"/>
<xs:attribute name="color" type="colorType" use="required"/>
</xs:complexType>
<xs:complexType name="listType">
<xs:attribute name="sortBy" type="sortType" use="required"/>
</xs:complexType>
<!--    definition of elements    -->
<xs:element name="commands">
<xs:complexType>
<xs:sequence>
<xs:choice minOccurs="0" maxOccurs="unbounded">
<xs:element name="createCity" type="cityType"/>
<xs:element name="deleteCity" type="nameType"/>
<xs:element name="clearAll" type="emptyType"/>
<xs:element name="listCities" type="listType"/>
<xs:element name="printSGTree" type="emptyType"/>
<xs:element name="printBinarySearchTree" type="emptyType"/>
</xs:choice>
</xs:sequence>
<xs:attributeGroup ref="commandAtts"/>
</xs:complexType>
</xs:element>
</xs:schema>

=== zainbhaila/MeeshQuest/MeeshQuest-Part1/test/mytest-input-2.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part1in.xsd"
	spatialWidth="1024" spatialHeight="1024">
 <createCity name="Edinburgh" y="500" x="100" radius="0" color="red"/>
 <createCity name="Lisbon" x="100" y="100" radius="0" color="orange"/>
 <createCity name="Varna" x="100" y="800" radius="0" color="red"/>
 <createCity name="London" x="150" y="250" radius="0" color="yellow"/>
 <createCity name="Prague" x="150" color="green" y="700" radius="0" />
 <printBinarySearchTree/>
 <printSGTree/>
 <createCity name="Madrid" x="200" y="100" radius="0" color="blue"/>
 <createCity name="Paris" x="250" y="300" radius="0" color="purple"/>
 <createCity name="Copenhagen" x="250" y="500" radius="0" color="black"/>
 <createCity name="Marseilles" x="350" y="100" radius="0" color="red"/>
 <createCity name="Vienna" x="350" y="700" radius="0" color="orange"/>
 <createCity name="Amsterdam" x="400" y="300" radius="0" color="yellow"/>
 <createCity name="Munich" x="400" y="200" radius="0" color="green"/>
 <createCity name="Milan" x="500" y="50" radius="0" color="blue"/>
 <createCity name="Rome" x="500" y="450" radius="0" color="purple"/>
 <createCity name="Naples" x="450" y="650" radius="0" color="black"/>
 <createCity name="Geneva" x="300" y="200" radius="0" color="orange"/>
 <createCity name="Geneva_Duplicate" y="200" x="300" radius="1" color="black"/>
 <printBinarySearchTree/>
 <printSGTree/>
 <deleteCity name="London"/>
 <deleteCity name="Marseilles"/>
 <deleteCity name="Amsterdam"/>
 <deleteCity name="Rome"/>
 <deleteCity name="London"/>
 <printBinarySearchTree/>
 <printSGTree/>
 <listCities sortBy="name"/>
 <clearAll/>
 <printSGTree/>
 <printBinarySearchTree/>
 <listCities sortBy="coordinate"/>
 </commands>

=== zainbhaila/MeeshQuest/MeeshQuest-Part1/test/mytest-input-5.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part1in.xsd"
	spatialWidth="1024" spatialHeight="1024">
 <createCity name="x21" x="21" y="0" radius="0" color="black"/>
 <createCity name="x64" x="64" y="0" radius="0" color="black"/>
 <createCity name="x06" x="06" y="0" radius="0" color="black"/>
 <createCity name="x60" x="60" y="0" radius="0" color="black"/>
 <createCity name="x90" x="90" y="0" radius="0" color="black"/>
 <createCity name="x08" x="08" y="0" radius="0" color="black"/>
 <createCity name="x22" x="22" y="0" radius="0" color="black"/>
 <createCity name="x63" x="63" y="0" radius="0" color="black"/>
 <createCity name="x19" x="19" y="0" radius="0" color="black"/>
 <createCity name="x16" x="16" y="0" radius="0" color="black"/>
 <createCity name="x02" x="02" y="0" radius="0" color="black"/>
 <createCity name="x96" x="96" y="0" radius="0" color="black"/>
 <createCity name="x09" x="09" y="0" radius="0" color="black"/>
 <createCity name="x87" x="87" y="0" radius="0" color="black"/>
 <createCity name="x89" x="89" y="0" radius="0" color="black"/>
 <createCity name="x58" x="58" y="0" radius="0" color="black"/>
 <createCity name="x23" x="23" y="0" radius="0" color="black"/>
 <createCity name="x55" x="55" y="0" radius="0" color="black"/>
 <createCity name="x65" x="65" y="0" radius="0" color="black"/>
 <createCity name="x97" x="97" y="0" radius="0" color="black"/>
 <createCity name="x03" x="03" y="0" radius="0" color="black"/>
 <createCity name="x30" x="30" y="0" radius="0" color="black"/>
 <createCity name="x40" x="40" y="0" radius="0" color="black"/>
 <createCity name="x79" x="79" y="0" radius="0" color="black"/>
 <createCity name="x77" x="77" y="0" radius="0" color="black"/>
 <createCity name="x39" x="39" y="0" radius="0" color="black"/>
 <createCity name="x47" x="47" y="0" radius="0" color="black"/>
 <createCity name="x46" x="46" y="0" radius="0" color="black"/>
 <createCity name="x14" x="14" y="0" radius="0" color="black"/>
 <createCity name="x42" x="42" y="0" radius="0" color="black"/>
 <createCity name="x05" x="05" y="0" radius="0" color="black"/>
 <createCity name="x86" x="86" y="0" radius="0" color="black"/>
 <createCity name="x27" x="27" y="0" radius="0" color="black"/>
 <createCity name="x67" x="67" y="0" radius="0" color="black"/>
 <createCity name="x28" x="28" y="0" radius="0" color="black"/>
 <createCity name="x61" x="61" y="0" radius="0" color="black"/>
 <createCity name="x91" x="91" y="0" radius="0" color="black"/>
 <createCity name="x72" x="72" y="0" radius="0" color="black"/>
 <createCity name="x74" x="74" y="0" radius="0" color="black"/>
 <createCity name="x51" x="51" y="0" radius="0" color="black"/>
 <createCity name="x37" x="37" y="0" radius="0" color="black"/>
 <createCity name="x01" x="01" y="0" radius="0" color="black"/>
 <createCity name="x00" x="00" y="0" radius="0" color="black"/>
 <createCity name="x32" x="32" y="0" radius="0" color="black"/>
 <createCity name="x33" x="33" y="0" radius="0" color="black"/>
 <createCity name="x04" x="04" y="0" radius="0" color="black"/>
 <createCity name="x68" x="68" y="0" radius="0" color="black"/>
 <createCity name="x44" x="44" y="0" radius="0" color="black"/>
 <createCity name="x73" x="73" y="0" radius="0" color="black"/>
 <createCity name="x17" x="17" y="0" radius="0" color="black"/>
 <createCity name="x85" x="85" y="0" radius="0" color="black"/>
 <createCity name="x76" x="76" y="0" radius="0" color="black"/>
 <createCity name="x10" x="10" y="0" radius="0" color="black"/>
 <createCity name="x92" x="92" y="0" radius="0" color="black"/>
 <createCity name="x70" x="70" y="0" radius="0" color="black"/>
 <createCity name="x26" x="26" y="0" radius="0" color="black"/>
 <createCity name="x50" x="50" y="0" radius="0" color="black"/>
 <createCity name="x13" x="13" y="0" radius="0" color="black"/>
 <createCity name="x43" x="43" y="0" radius="0" color="black"/>
 <createCity name="x38" x="38" y="0" radius="0" color="black"/>
 <createCity name="x99" x="99" y="0" radius="0" color="black"/>
 <createCity name="x45" x="45" y="0" radius="0" color="black"/>
 <createCity name="x54" x="54" y="0" radius="0" color="black"/>
 <createCity name="x94" x="94" y="0" radius="0" color="black"/>
 <createCity name="x15" x="15" y="0" radius="0" color="black"/>
 <createCity name="x78" x="78" y="0" radius="0" color="black"/>
 <createCity name="x12" x="12" y="0" radius="0" color="black"/>
 <createCity name="x34" x="34" y="0" radius="0" color="black"/>
 <createCity name="x57" x="57" y="0" radius="0" color="black"/>
 <createCity name="x53" x="53" y="0" radius="0" color="black"/>
 <createCity name="x84" x="84" y="0" radius="0" color="black"/>
 <createCity name="x25" x="25" y="0" radius="0" color="black"/>
 <createCity name="x18" x="18" y="0" radius="0" color="black"/>
 <createCity name="x69" x="69" y="0" radius="0" color="black"/>
 <createCity name="x35" x="35" y="0" radius="0" color="black"/>
 <createCity name="x80" x="80" y="0" radius="0" color="black"/>
 <createCity name="x59" x="59" y="0" radius="0" color="black"/>
 <createCity name="x11" x="11" y="0" radius="0" color="black"/>
 <createCity name="x07" x="07" y="0" radius="0" color="black"/>
 <createCity name="x29" x="29" y="0" radius="0" color="black"/>
 <createCity name="x36" x="36" y="0" radius="0" color="black"/>
 <createCity name="x81" x="81" y="0" radius="0" color="black"/>
 <createCity name="x52" x="52" y="0" radius="0" color="black"/>
 <createCity name="x66" x="66" y="0" radius="0" color="black"/>
 <createCity name="x71" x="71" y="0" radius="0" color="black"/>
 <createCity name="x83" x="83" y="0" radius="0" color="black"/>
 <createCity name="x56" x="56" y="0" radius="0" color="black"/>
 <createCity name="x82" x="82" y="0" radius="0" color="black"/>
 <createCity name="x95" x="95" y="0" radius="0" color="black"/>
 <createCity name="x75" x="75" y="0" radius="0" color="black"/>
 <createCity name="x62" x="62" y="0" radius="0" color="black"/>
 <createCity name="x24" x="24" y="0" radius="0" color="black"/>
 <createCity name="x20" x="20" y="0" radius="0" color="black"/>
 <createCity name="x41" x="41" y="0" radius="0" color="black"/>
 <createCity name="x88" x="88" y="0" radius="0" color="black"/>
 <createCity name="x93" x="93" y="0" radius="0" color="black"/>
 <createCity name="x31" x="31" y="0" radius="0" color="black"/>
 <createCity name="x98" x="98" y="0" radius="0" color="black"/>
 <createCity name="x49" x="49" y="0" radius="0" color="black"/>
 <createCity name="x48" x="48" y="0" radius="0" color="black"/>
 <printBinarySearchTree/>
 <printSGTree/>
 </commands>

=== zainbhaila/MeeshQuest/MeeshQuest-Part1/test/mytest-input-4.xml
<commands
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="part1in.xsd"
	spatialWidth="1024" spatialHeight="1024">
 <printSGTree/>
 <createCity name="x06" x="6" y="0" radius="0" color="black"/>
 <createCity name="x10" x="10" y="0" radius="0" color="black"/>
 <createCity name="x12" x="12" y="0" radius="0" color="black"/>
 <createCity name="x16" x="16" y="0" radius="0" color="black"/>
 <printSGTree/>
 <createCity name="x18" x="18" y="0" radius="0" color="black"/>
 <printSGTree/>
 <createCity name="x20" x="20" y="0" radius="0" color="black"/>
 <createCity name="x04" x="4" y="0" radius="0" color="black"/>
 <createCity name="x14" x="14" y="0" radius="0" color="black"/>
 <createCity name="x02" x="2" y="0" radius="0" color="black"/>
 <createCity name="x08" x="8" y="0" radius="0" color="black"/>
 <printSGTree/>
 <createCity name="x00" x="0" y="0" radius="0" color="black"/>
 <printSGTree/>
 <printBinarySearchTree/>
 </commands>
